apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: balloon-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/AndrejBardakoski/KIII-Project.git
    targetRevision: HEAD
    path: "K8S manifests"

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 10s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 1m # the maximum amount of time allowed for the backoff strategy

  revisionHistoryLimit: 5