version: "3"
services:
  pgsql-db:
    image: postgres
    container_name: "postgres_DB"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  spring-app:
    image: andre102/balloon_app:latest
    container_name: "devops_app"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    depends_on:
      - pgsql-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgsql-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123