kind: ConfigMap
apiVersion: v1
metadata:
  namespace: kiii-project
  name: db-config-map
data:
  db_user: postgres
  db_name: postgres
  db_url: jdbc:postgresql://postgresql-database-master-service.kiii-project.svc.cluster.local:5432/postgres
  db_replica_user: repl_user
  db_master_host: postgresql-database-master-service.kiii-project.svc.cluster.local