kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-database-master-pvc
  namespace: kiii-project
spec:
  storageClassName: local-path
  capacity:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi