apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-database-master-deployment
  namespace: kiii-project
spec:
  replicas: 1
  selector:
    matchLabels:
      database: master
      project: kiii_project
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        database: master
        project: kiii_project
    spec:
      containers:
        - name: postgresql-database-master-pod
          image: bitnami/postgresql:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-master-data
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRESQL_REPLICATION_MODE
              value: master
            - name: POSTGRESQL_REPLICATION_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config-map
                  key: db_replica_user
            - name: POSTGRESQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-config-map
                  key: db_user
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: db-config-map
                  key: db_name
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_password
            - name: POSTGRESQL_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db_replica_password
      volumes:
        - name: postgresql-master-data
          persistentVolumeClaim:
            claimName: postgresql-database-master-pvc