apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
  namespace: kiii-project
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    framework: spring_boot
    project: kiii_project
    title: balloon_app